# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

class Contents(object):
    NONE = 0
    HealthContents = 1
    OrderContents = 2
    ResponseContents = 3
