# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CustomAppProto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HealthBody(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HealthBody()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHealthBody(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HealthBody
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HealthBody
    def Dispenser(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HealthBody
    def Icemaker(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthBody
    def Lightbulb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HealthBody
    def FridgeTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthBody
    def FreezerTemp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # HealthBody
    def SensorStatus(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # HealthBody
    def Humidity(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

    # HealthBody
    def DoorOpenings(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def HealthBodyStart(builder):
    builder.StartObject(8)

def Start(builder):
    HealthBodyStart(builder)

def HealthBodyAddDispenser(builder, dispenser):
    builder.PrependInt8Slot(0, dispenser, 0)

def AddDispenser(builder, dispenser):
    HealthBodyAddDispenser(builder, dispenser)

def HealthBodyAddIcemaker(builder, icemaker):
    builder.PrependInt32Slot(1, icemaker, 0)

def AddIcemaker(builder, icemaker):
    HealthBodyAddIcemaker(builder, icemaker)

def HealthBodyAddLightbulb(builder, lightbulb):
    builder.PrependInt8Slot(2, lightbulb, 0)

def AddLightbulb(builder, lightbulb):
    HealthBodyAddLightbulb(builder, lightbulb)

def HealthBodyAddFridgeTemp(builder, fridgeTemp):
    builder.PrependInt32Slot(3, fridgeTemp, 0)

def AddFridgeTemp(builder, fridgeTemp):
    HealthBodyAddFridgeTemp(builder, fridgeTemp)

def HealthBodyAddFreezerTemp(builder, freezerTemp):
    builder.PrependInt32Slot(4, freezerTemp, 0)

def AddFreezerTemp(builder, freezerTemp):
    HealthBodyAddFreezerTemp(builder, freezerTemp)

def HealthBodyAddSensorStatus(builder, sensorStatus):
    builder.PrependInt8Slot(5, sensorStatus, 0)

def AddSensorStatus(builder, sensorStatus):
    HealthBodyAddSensorStatus(builder, sensorStatus)

def HealthBodyAddHumidity(builder, humidity):
    builder.PrependFloat64Slot(6, humidity, 0.0)

def AddHumidity(builder, humidity):
    HealthBodyAddHumidity(builder, humidity)

def HealthBodyAddDoorOpenings(builder, doorOpenings):
    builder.PrependUint32Slot(7, doorOpenings, 0)

def AddDoorOpenings(builder, doorOpenings):
    HealthBodyAddDoorOpenings(builder, doorOpenings)

def HealthBodyEnd(builder):
    return builder.EndObject()

def End(builder):
    return HealthBodyEnd(builder)
