# Download base image ubuntu 22.04

FROM ubuntu:22.04

# LABEL about the custom image

LABEL maintainer="jackson.m.shelby@vanderbilt.edu"


LABEL version="0.1"

LABEL description="This is a custom Docker Image for Protobuf compiled on M1."

# Disable Prompt During Packages Installation

ARG DEBIAN_FRONTEND=noninteractive

# Install the key packages

RUN apt-get -y update && apt-get install -y cmake git gcc g++ clang default-jdk python3-dev python3-pip wget net-tools dnsutils iputils-ping iputils-tracepath iputils-arping iputils-clockdiff inetutils-traceroute emacs vim libzmq3-dev protobuf-compiler

# Upgrade pip to the latest version

RUN python3 -m pip install --upgrade pip

# Install any python packages

RUN python3 -m pip install --upgrade grpcio grpcio-tools

WORKDIR /work

# Copy all of the files and directories from current directory 

# to the current directory within the container

COPY ProtocolBuffers/fridge_grpc_client.py .
COPY ProtocolBuffers/grocery_grpc_server.py .
COPY ProtocolBuffers/health_grpc_server.py .
COPY ProtocolBuffers/schema.proto .
COPY ProtocolBuffers/schema_pb2.py .
COPY ProtocolBuffers/schema_pb2.pyi .
COPY ProtocolBuffers/schema_pb2_grpc.py .

